config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,skip:[:registrations,:passwords],controllers:{
    sessions:"admin/sessions"
  }

  devise_for :users,controllers:{
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :admin do
    root to: "homes#top"
    resources :genres, only:[:new,:create,:index,:edit,:update,:destroy]
    resources :recommend_gifts, only:[:new,:create,:index,:edit,:update,:destroy,:show]
  end

  scope module: :public do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :users, only:[:show,:edit,:update]
    resources :genres, only:[:index]
    resources :recommend_gifts, only:[:index,:show]
    resources :friends, only:[:index,:new,:create,:edit,:update,:destroy]
    resources :present_lists, only:[:index,:create,:edit,:update,:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="content has-text-centered">
    <p class="has-text-dark">&copy; 2022
    </p>
    <a href="https://developers.rakuten.com/" target="_blank">Supported by Rakuten Developers</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand pt-3 px-6">

      <%= link_to root_path, class:"header-title" do %>
        <h1 class="title">GIFTEMO</h1>
        <h2 class="subtitle">Leave as a memory.</h2>
      <% end %>
    </div>
    <!--</section>-->
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="menu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>

    <div id="menu" class="navbar-menu">

      <div class="navbar-end">
        <% if user_signed_in? %>

          <div class="nav-item">
            <%= link_to user_path(current_user), class:"link" do %>
              <i class="fa fa-smile"> マイページ</i>
            <% end %>
          </div><br>
          <div class="nav-item">
            <%= link_to destroy_user_session_path, method: :delete, class:"link" do %>
              <i class="fa fa-lock "> ログアウト</i>
            <% end %>
          </div>

          <% else %>
            <div class="nav-item">
              <%= link_to new_user_registration_path, class:"link-1" do %>
                <span><i class="fa fa-user"></i> 新規登録</span>
              <% end %>
            </div><br>
            <div class="nav-item">
              <%= link_to new_user_session_path, class:"link-1" do %>
                <span><i class="fa fa-unlock-alt "></i> ログイン</span>
              <% end %>
            </div><br>
            <div class="nav-item">
              <%= link_to users_guest_sign_in_path, method: :post, class:"link" do %>
                <span><i class="fa fa-user-secret "></i> ゲストログイン</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
  </nav>
</header>

app/views/layouts/_list.html.erb
<input type="checkbox" class="openSidebarMenu" id="openSidebarMenu">
  <label for="openSidebarMenu" class="sidebarIconToggle">
    <div class="spinner diagonal part-1"></div>
    <div class="spinner horizontal"></div>
    <div class="spinner diagonal part-2"></div>
  </label>

<div id="sidebarMenu">
  <ul class="sidebarMenuInner">
    <li><a><%= link_to "おともだちリスト", friends_path %></a></li>
    <li><a><%= link_to "ギフトリスト", present_lists_path %></a></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GIFTEMO</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/c05e50022c.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  </head>


  <body style="background-color: #BC8F8F">
    <%= render 'layouts/header' %>

    <main>
      <div class="flash" style="px-6">
        <%= flash[:notice] %>
      </div>
        <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>